// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain


// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> _OldStateMap;
RWTexture2D<float4> _NewStateMap;
float _DeltaTime;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 old_state = _OldStateMap[id.xy];
    old_state.y += _DeltaTime;
    _NewStateMap[id.xy] = old_state;
}
